// Code generated by entc, DO NOT EDIT.

package ent

import (
	"ent-graphql/ent/note"
	"ent-graphql/ent/schema"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	noteMixin := schema.Note{}.Mixin()
	noteMixinFields0 := noteMixin[0].Fields()
	_ = noteMixinFields0
	noteFields := schema.Note{}.Fields()
	_ = noteFields
	// noteDescCreateTime is the schema descriptor for create_time field.
	noteDescCreateTime := noteMixinFields0[0].Descriptor()
	// note.DefaultCreateTime holds the default value on creation for the create_time field.
	note.DefaultCreateTime = noteDescCreateTime.Default.(func() time.Time)
	// noteDescUpdateTime is the schema descriptor for update_time field.
	noteDescUpdateTime := noteMixinFields0[1].Descriptor()
	// note.DefaultUpdateTime holds the default value on creation for the update_time field.
	note.DefaultUpdateTime = noteDescUpdateTime.Default.(func() time.Time)
	// note.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	note.UpdateDefaultUpdateTime = noteDescUpdateTime.UpdateDefault.(func() time.Time)
}
